### ISSUE TITLE
Trying to reproduce and getting "Cannot read property 'req' of undefined"

### ISSUE THREAD

**Issue by Vadorequest** [tomanagle/apollo-example#2]
I'm cloned and tested you repository, it works well, thanks for that!

I'm beginning a new Next.js project and I used to use HOC for GraphQL, but this new way seems better indeed. But when I try to apply what you did, I get the following:

```
Cannot read property 'req' of undefined
TypeError: Cannot read property 'req' of undefined
    at /Users/vadorequest/dev/TFP/node_modules/next-with-apollo/lib/withApollo.js:109:43
    at step (/Users/vadorequest/dev/TFP/node_modules/next-with-apollo/lib/withApollo.js:56:23)
    at Object.next (/Users/vadorequest/dev/TFP/node_modules/next-with-apollo/lib/withApollo.js:37:53)
    at /Users/vadorequest/dev/TFP/node_modules/next-with-apollo/lib/withApollo.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/vadorequest/dev/TFP/node_modules/next-with-apollo/lib/withApollo.js:27:12)
    at Function._a.getInitialProps (/Users/vadorequest/dev/TFP/node_modules/next-with-apollo/lib/withApollo.js:103:61)
    at loadGetInitialProps (/Users/vadorequest/dev/TFP/.next/server/static/development/pages/_document.js:530:33)
    at Function.<anonymous> (/Users/vadorequest/dev/TFP/.next/server/static/development/pages/_app.js:2154:58)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/vadorequest/dev/TFP/.next/server/static/development/pages/_document.js:217:24)
    at _next (/Users/vadorequest/dev/TFP/.next/server/static/development/pages/_document.js:239:9)
    at /Users/vadorequest/dev/TFP/.next/server/static/development/pages/_document.js:246:7
    at new Promise (<anonymous>)
    at new F (/Users/vadorequest/dev/TFP/node_modules/core-js/library/modules/_export.js:36:28)
    at Function.<anonymous> (/Users/vadorequest/dev/TFP/.next/server/static/development/pages/_document.js:235:12)
```

Here is a diff between my older version (HOC) and the new one (hooks): 
https://diffy.org/diff/ob877mfdeqeix8r487s3jtt9

Not directly related to the issue, but one of the reason why I wanted to update my existing code is that I figured that my app isn't doing SSR at all, I wonder if that's related to the `<ApolloProvider client={apollo}>`, I didn't wrap my app in an ApolloProvider.

**Comment by Vadorequest** [comment]
Well, I have no idea where the problem was, but I fixed it by applying part of your code on top of mine bit by bit until it magically worked.
